# pyproject.toml

[tool.pytest.ini_options]
minversion = "6.0"
# TODO: Update this to look for tests in a more specific location
addopts = "--cov-report xml:coverage.xml --cov=."
testpaths = [
    "tests",
]
